#! /usr/bin/perl#
# Example using the continue block
for ($i=1; $i<=10; $i++) {      # $i is incremented only once
	if ($i==5){
		print "\$i == $i\n";
		next;
	}
	print "$i ";
}

print "\n"; print '=' x 35; print "\n";
# ---------------------------------------------------------

$i=1;
while ($i <= 10){
	if ($i==5){
		print "\$i == $i\n";
		$i++;    # $i must be incremented here or an 
		         # infinite loop will start
		next;
	}
	print "$i ";
	$i++;           # $i is incremented again
}

print "\n"; print '=' x 35; print "\n";
# -------------------------------------------------------
# The continue block allows the while loop to act like a for loop
$i=1;
while ($i <= 10) {
	if ($i == 5) {
		print "\$i == $i\n";
		next;
	}
	print "$i ";
}continue {$i++; }    # $i is incremented only once
