#!/bin/perl
{ package Grandpa;
  $name = "Gramps";
  sub greetme {
	  print "Hi $Child::name I'm your $name from package 
         Grandpa.\n";
   }
}
{ package Parent;
	# This package is empty
}
{ package Child;
$name = "Baby";
print "Hi I'm $name in the Child Package here.\n";
Parent->greetme();
}
package UNIVERSAL;
sub AUTOLOAD {
	print "The UNIVERSAL lookup package.\n";
	Grandpa->greetme();
}

