#!/usr/bin/perl
use CGI;
$query = new CGI;  
# Create a CGI object
print $query->header;
print $query->start_html("Forms and Text Fields");
print  $query->h2("Example: The textfield method");

&print_form($query);
&do_work($query) if ($query->param);
print $query->end_html;

sub print_form{
	my($query) = @_;
	print $query->startform;
	print "What is your name? ";
	print $query->textfield('name');  # A simple text field
	print  $query->br();
	print "What is your occupation? ";
	print $query->textfield(-name=>'occupation',  # Giving values
	                        -default=>'Retired',  # to the
	                        -size=>60,            # text field
	                        -maxlength=>120,
	                       );
	print $query->br();
	print $query->submit('action', 'Enter ');
	print $query->reset();
	print $query->endform;
	print $query->hr();
}

sub do_work{
	my ($query) = @_;
	my (@values, $key);
	print $query->("<H2>Here are the settings</H2>");
	foreach $key ($query->param){
		print "$key: \n";
		@values=$query->param($key);
		print join(", ",@values), "<BR>";
	}
}