#!/bin/perl
print "Content type: text/plain\n\n";
print "CGI/1.1 test script report:\n\n";
# Print out all the environment variables
while(($key, $value)=each(%ENV)){
	print "$key = $value\n";
}